version: '3.8'

services:
  # Apprise-Go API Server
  apprise-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apprise-go-api
    ports:
      - "8080:8080"
    environment:
      - APPRISE_PORT=8080
      - APPRISE_HOST=0.0.0.0
      - APPRISE_LOG_LEVEL=info
      - APPRISE_ENABLE_CORS=true
      - APPRISE_MAX_REQUESTS_PER_MINUTE=100
    volumes:
      - ./configs:/home/apprise/configs:ro
      - apprise-data:/home/apprise/data
    networks:
      - apprise-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: apprise-go-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - apprise-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: apprise-go-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - apprise-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  # Grafana for monitoring dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: apprise-go-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - apprise-network
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  apprise-data:
    driver: local
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  apprise-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16