apiVersion: v1
kind: Namespace
metadata:
  name: apprise-go
  labels:
    name: apprise-go
    app: apprise-go
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apprise-go-service-account
  namespace: apprise-go
  labels:
    app: apprise-go
automountServiceAccountToken: false