apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprise-go-data
  namespace: apprise-go
  labels:
    app: apprise-go
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd